# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: some_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - somenet
    command: ["--character-set-server=utf8", "--collation-serer=utf8_unicode_ci"]
    


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - somenet

networks:
  somenet:
    driver: bridge

volumes:
  mariadb-data:
